# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  BINARY: '{{if eq OS "windows"}}claude-bot.exe{{else}}claude-bot{{end}}'

tasks:
  default:
    desc: Build the binary
    sources: ["*.go", "go.mod"]
    generates: ["{{.BINARY}}"]
    cmds:
      - go build -o {{.BINARY}} .

  test:
    desc: Run unit tests
    cmds:
      - go test -v -count=1 ./...

  test-integration:
    desc: Run integration tests (creates/deletes a test repo on GitHub)
    env:
      CB_INTEGRATION: "1"
    cmds:
      - go test -v -run TestIntegration -count=1 -timeout 120s

  start:
    desc: Build and run claude-bot (idempotent — no-op if already running)
    deps: [default]
    cmds:
      - |
        if pgrep -f './claude-bot' > /dev/null 2>&1; then
          echo "claude-bot already running"
        else
          nohup ./{{.BINARY}} >> ~/.claude-bot/bot.log 2>&1 &
          echo "claude-bot started (logs at ~/.claude-bot/bot.log)"
        fi

  stop:
    desc: Stop claude-bot (idempotent — no-op if not running)
    cmds:
      - pkill -f './claude-bot' 2>/dev/null && echo "claude-bot stopped" || echo "claude-bot not running"

  restart:
    desc: Stop and start claude-bot
    cmds:
      - task: stop
      - task: start

  clean:
    desc: Remove build artifacts and bot state
    cmds:
      - task: stop
      - cmd: rm -f {{.BINARY}}
        platforms: [linux, darwin]
      - cmd: del /f {{.BINARY}} 2>nul
        platforms: [windows]
      - cmd: rm -rf ~/.claude-bot/trees ~/.claude-bot/logs
        platforms: [linux, darwin]
      - cmd: rd /s /q "%USERPROFILE%\.claude-bot\trees" "%USERPROFILE%\.claude-bot\logs" 2>nul
        platforms: [windows]
