# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    desc: Build the binary (via Go self-build)
    sources: ["*.go", "go.mod"]
    generates: ["claude-bot"]
    cmds:
      - go run . --build

  test:
    desc: Run unit tests
    cmds:
      - go test -v -count=1 ./...

  test-integration:
    desc: Run integration tests (creates/deletes a test repo on GitHub)
    env:
      CB_INTEGRATION: "1"
    cmds:
      - go test -v -run TestIntegration -count=1 -timeout 120s

  release:
    desc: Cross-compile all targets and publish GitHub release
    cmds:
      - go run . --release

  update:
    desc: Self-update from latest GitHub release
    cmds:
      - go run . --update

  start:
    desc: Build and run claude-bot (idempotent — no-op if already running)
    deps: [default]
    cmds:
      - |
        if pgrep -f './claude-bot' > /dev/null 2>&1; then
          echo "claude-bot already running"
        else
          nohup ./claude-bot >> ~/.claude-bot/bot.log 2>&1 &
          echo "claude-bot started (logs at ~/.claude-bot/bot.log)"
        fi

  stop:
    desc: Stop claude-bot (idempotent — no-op if not running)
    cmds:
      - pkill -f './claude-bot' 2>/dev/null && echo "claude-bot stopped" || echo "claude-bot not running"

  restart:
    desc: Stop and start claude-bot
    cmds:
      - task: stop
      - task: start

  clean:
    desc: Remove build artifacts and bot state
    cmds:
      - task: stop
      - rm -f claude-bot claude-bot.exe
      - rm -rf ~/.claude-bot/trees ~/.claude-bot/logs
